### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by bhavdeep98** [llamazing/numnet_plus#15]
11/02/2020 07:49:01 Num update steps 379535!
11/02/2020 07:49:01 Build bert model.
11/02/2020 07:49:13 Build Drop model.
11/02/2020 07:49:14 Build optimizer etc...
11/02/2020 07:49:19 At epoch 1
Traceback (most recent call last):
  File "./roberta_gcn_cli.py", line 103, in <module>
    main()
  File "./roberta_gcn_cli.py", line 82, in main
    model.update(batch)
  File "/home/bssachde/numnet/numnet_plus/tools/model.py", line 47, in update
    output_dict = self.mnetwork(**tasks)
  File "/home/bssachde/.conda/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bssachde/numnet/numnet_plus/mspan_roberta_gcn/mspan_roberta_gcn.py", line 167, in forward
    sequence_output_list = [ item for item in outputs[2][-4:] ]
IndexError: tuple index out of range

I am getting the above error when using the Numnet_plus code directly by accessing Github without any changes. As far as I remember this kind of issue usually occurred for migrating between pytorch-pretrained-bert and transformers but I am not able to figure out where to make changes here. Could anyone help me out here?

**Comment by danyaljj** [comment]
This might be due to your pytorch transformers version. 
Try installing an older version: 
```
pip uninstall pytorch-transformers 
pip uninstall transformers 
pip install pytorch-transformers==1.1.0
```

**Comment by danyaljj** [comment]
I'm sorry, scratch what I said. The issue is that you need to update your config file, as it's explained in the readme. 
<img width="822" alt="Screen Shot 2020-11-19 at 11 27 57 PM" src="https://user-images.githubusercontent.com/2441454/99772011-dd4e9680-2abe-11eb-8404-0549b47f6271.png">
