### ISSUE TITLE
roberta config fail?

### ISSUE THREAD

**Issue by mx8435** [llamazing/numnet_plus#2]
Hi, I follow the README.md but got the following error:

```
_proj_sequence_g2.ln.bias torch.Size([1024])
_proj_sequence_g2.fc2.weight torch.Size([1, 1024])
_proj_sequence_g2.fc2.bias torch.Size([1])
_proj_span_num.fc1.weight torch.Size([1024, 3072])
_proj_span_num.fc1.bias torch.Size([1024])
_proj_span_num.ln.weight torch.Size([1024])
_proj_span_num.ln.bias torch.Size([1024])
_proj_span_num.fc2.weight torch.Size([9, 1024])
_proj_span_num.fc2.bias torch.Size([9])
10/22/2019 03:58:45 Build optimizer etc...
10/22/2019 03:58:50 At epoch 1
Traceback (most recent call last):
  File "./roberta_gcn_cli.py", line 90, in <module>
    main()
  File "./roberta_gcn_cli.py", line 69, in main
    model.update(batch)
  File "/home/admin/torch/raw_roberta/numnet_plus/tools/model.py", line 47, in update
    output_dict = self.mnetwork(**tasks)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin/torch/raw_roberta/numnet_plus/mspan_roberta_gcn/mspan_roberta_gcn.py", line 169, in forward
    sequence_output_list = [ item for item in outputs[2][-4:] ]
IndexError: tuple index out of range
```
Should we set `output_hidden_states=true` ?
![image](https://user-images.githubusercontent.com/8417466/67305729-68f69c00-f528-11e9-8db0-b32e1251cfa5.png)

**Comment by llamazing** [comment]
Sorry for the mistake. 
Yes, you should set `output_hidden_states=true`.
