### ISSUE TITLE
Error in roberta_gcn_cli.py

### ISSUE THREAD

**Issue by ShuGao0810** [llamazing/numnet_plus#4]
Traceback (most recent call last):
 File "./roberta_gcn_cli.py", line 94, in <module>
   main()
 File "./roberta_gcn_cli.py", line 72, in main
   model.update(batch)
 File "/data/gaoshu562/DROP/numnet_plus-master/tools/model.py", line 47, in update
   output_dict = self.mnetwork(**tasks)
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
   result = self.forward(*input, **kwargs)
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 144, in forward
   return self.gather(outputs, self.output_device)
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in gather
   return gather(outputs, output_device, dim=self.dim)
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
   return gather_map(outputs)
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in gather_map
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in <genexpr>
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
   return type(out)(map(gather_map, zip(*outputs)))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in gather_map
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in <genexpr>
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
   return type(out)(map(gather_map, zip(*outputs)))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in gather_map
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 61, in <genexpr>
   for k in out))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
   return type(out)(map(gather_map, zip(*outputs)))
 File "/data/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
   return type(out)(map(gather_map, zip(*outputs)))
TypeError: zip argument #1 must support iteration

**Comment by llamazing** [comment]
I think this is because you use multi-GPU when training. The code does not support multi-GPU training now.

**Comment by ShuGao0810** [comment]
> I think this is because you use multi-GPU when training. The code does not support multi-GPU training now.

You're right, there is no such problem with a single GPU.
